services:
  app:
    build:
      context: .
    container_name: app
    volumes:
      - ./data:/data
    environment:
      - DB_FILE=/data/db.sqlite3
      - PW_SERVER=ws://pw:3000/
      - PATH=/src/.venv/bin:$PATH
    env_file:
      - .env
    links:
      - pw
    depends_on:
      - pw
    command: daphne -b 0.0.0.0 -p 8000 byos_django.asgi:application
    develop:
      watch:
        - action: sync
          path: .
          target: /src
          ignore:
            - .venv/
        - action: rebuild
          path: uv.lock
  pw:
    image: mcr.microsoft.com/playwright:v1.50.0-noble
    container_name: pw
    user: pwuser
    init: true
    volumes:
      - pw_home:/home/pwuser
    command: npx -y playwright@1.50.0 run-server --port 3000 --host 0.0.0.0
  nginx:
    build:
      context: .
    container_name: nginx
    ports:
      - "8000:80"
    links:
      - app
    depends_on:
      - app
    command: nginx -g 'daemon off;'
    develop:
      watch:
        - action: sync+restart
          path: ./etc/nginx.conf
          target: /etc/nginx/sites-available/default
volumes:
  pw_home:
