x-logging: &default-logging
  driver: json-file
  options:
    max-size: "15m"
    max-file: "3"

services:
  app:
    image: trmnl_app:latest
    build:
      context: .
    container_name: trmnl_django_app
    volumes:
      - trmnl-django-static:/src/static
      - .:/src
      - venv-volume:/src/.venv
      - ./data:/data
    environment:
      - DB_FILE=/data/db.sqlite3
      - PW_SERVER=ws://pw:3000/
      - PATH=/src/.venv/bin:$PATH
    networks:
      - main
    env_file:
      - .env
    depends_on:
      - pw
      - redis
    # command: daphne -b 0.0.0.0 -p 8000 byos_django.asgi:application
    command: python manage.py runserver 0.0.0.0:8000
    logging: *default-logging
  scheduler:
    image: trmnl_app:latest
    build:
      context: .
    container_name: trmnl_django_scheduler
    volumes:
      - .:/src
      - venv-volume:/src/.venv
      - ./data:/data
    environment:
      - DB_FILE=/data/db.sqlite3
      - PW_SERVER=ws://pw:3000/
      - PATH=/src/.venv/bin:$PATH
    networks:
      - main
    env_file:
      - .env
    depends_on:
      - pw
      - redis
    command: python manage.py rqworker default
    logging: *default-logging
  pw:
    image: mcr.microsoft.com/playwright:v1.50.0-noble
    container_name: trmnl_django_pw
    user: pwuser
    init: true
    volumes:
      - pw_home:/home/pwuser
    networks:
      - main
    command: npx -y playwright@1.50.0 run-server --port 3000 --host 0.0.0.0
    logging: *default-logging
  redis:
    image: redis:7
    container_name: redis
    volumes:
      - redis-data:/data
    networks:
      - main
    working_dir: /data
    logging: *default-logging
  nginx:
    image: nginx:1.27
    container_name: trmnl_django_nginx
    volumes:
      - trmnl-django-static:/src/static
      - ./etc/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"
    depends_on:
      - app
    networks:
      - main
    command: nginx -g 'daemon off;'
    develop:
      watch:
        - action: sync+restart
          path: ./etc/nginx.conf
          target: /etc/nginx/nginx.conf
    logging: *default-logging
volumes:
  pw_home:
  venv-volume:
  redis-data:
  trmnl-django-static:

networks:
  main:
    driver: bridge
