# Generated by Django 5.1.7 on 2025-03-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='config',
            field=models.JSONField(default=dict),
        ),
    ]
