# Generated by Django 5.1.7 on 2025-03-21 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0002_plugin_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='config',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='plugin_class',
            field=models.CharField(choices=[('plugins.idfm_metro.plugin.IdfmMetroPlugin', 'IdfmMetroPlugin'), ('plugins.whos_that_pokemon.plugin.PokemonPlugin', 'PokemonPlugin')], help_text='Python fullpath to the recipe class', max_length=255, unique=True, verbose_name='Recipe'),
        ),
    ]
