# Generated by Django 5.1.7 on 2025-03-21 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0003_alter_plugin_config_alter_plugin_plugin_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plugin',
            old_name='plugin_class',
            new_name='recipe',
        ),
    ]
