# Generated by Django 5.1.7 on 2025-03-22 21:57

import uuid

from django.db import migrations, models


def gen_uuid(apps, schema_editor):
    Plugin = apps.get_model("plugins", "Plugin")
    for row in Plugin.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("plugins", "0004_rename_plugin_class_plugin_recipe"),
    ]

    operations = [
        migrations.AddField(
            model_name="plugin",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, verbose_name="Public identifier"
            ),
        ),
        migrations.AlterField(
            model_name="plugin",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="plugin",
            name="recipe",
            field=models.CharField(
                choices=[
                    ("plugins.idfm_metro.plugin.IdfmMetroRecipe", "IdfmMetroRecipe"),
                    ("plugins.whos_that_pokemon.plugin.PokemonRecipe", "PokemonRecipe"),
                ],
                help_text="Python fullpath to the recipe class",
                max_length=255,
                unique=True,
                verbose_name="Recipe",
            ),
        ),
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
