# Generated by Django 5.1.7 on 2025-03-22 21:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0005_plugin_uuid_alter_plugin_name_alter_plugin_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plugin',
            name='id',
        ),
        migrations.AlterField(
            model_name='plugin',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Public identifier'),
        ),
    ]
