# Generated by Django 5.1.7 on 2025-03-23 22:09

import utils.weekday_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trmnl', '0005_apikey_updated_at_devicelog_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='weekdays',
            field=utils.weekday_field.WeekdaysField(default=0),
        ),
    ]
