# Generated by Django 5.1.7 on 2025-03-25 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trmnl', '0007_playlistitem_is_active_screen_playlist_item_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apikey',
            options={'ordering': ['-created_at', 'name'], 'verbose_name': 'API Key', 'verbose_name_plural': 'API Keys'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['-created_at', 'device_name'], 'verbose_name': 'Device', 'verbose_name_plural': 'Devices'},
        ),
        migrations.AlterModelOptions(
            name='devicelog',
            options={'ordering': ['-created_at', 'device'], 'verbose_name': 'Device Log', 'verbose_name_plural': 'Device Logs'},
        ),
        migrations.AlterModelOptions(
            name='screen',
            options={'ordering': ['-created_at', 'device'], 'verbose_name': 'Screen', 'verbose_name_plural': 'Screens'},
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='duration',
            field=models.PositiveIntegerField(blank=True, default=900, help_text='In seconds', verbose_name='Duration'),
        ),
    ]
