# Generated by Django 5.1.7 on 2025-03-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trmnl', '0008_alter_apikey_options_alter_device_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Name'),
        ),
    ]
